events {
    worker_connections 1024;
}

http {
    include      /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream indexer     { server indexing-server:42069; }
    upstream hola-modern { server hola-modern:80; }

    server {
        listen 80;
        server_name staging.hollab.io;

        location / {
            proxy_pass http://hola-modern;
            proxy_http_version 1.1;
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        }
    }

    server {
        listen 80;
        server_name indexer.hollab.io;

        location / {
            proxy_pass http://indexer;
            proxy_http_version 1.1;
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
            # WebSocket support (ponder live queries)
            proxy_set_header Upgrade           $http_upgrade;
            proxy_set_header Connection        "upgrade";
        }
    }
}
