export const ActionVotingAbi = [
    { type: "constructor", inputs: [], stateMutability: "nonpayable" },
    {
        type: "function",
        name: "castVote",
        inputs: [
            { name: "_voteId", type: "uint256", internalType: "uint256" },
            {
                name: "_support",
                type: "uint8",
                internalType: "enum HolacracyTypes.VoteSupport",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "orgFactory",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "contract IOrganizationFactory" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "createVote",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_outputId", type: "uint256", internalType: "uint256" },
            { name: "_reason", type: "string", internalType: "string" },
            { name: "_duration", type: "uint256", internalType: "uint256" },
        ],
        outputs: [{ name: "_voteId", type: "uint256", internalType: "uint256" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "getCircleMintCap",
        inputs: [{ name: "_circleId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "_cap", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getCircleMintedTotal",
        inputs: [{ name: "_circleId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "_total", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getCircleQuorum",
        inputs: [{ name: "_circleId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "_quorum", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getCollaboratorWeight",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_collaborator", type: "address", internalType: "address" },
        ],
        outputs: [{ name: "_weight", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getVoteWeight",
        inputs: [
            { name: "_voteId", type: "uint256", internalType: "uint256" },
            { name: "_voter", type: "address", internalType: "address" },
        ],
        outputs: [{ name: "_weight", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "govToken",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "contract IVotes" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "grantCollaboratorWeight",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_collaborator", type: "address", internalType: "address" },
            { name: "_weight", type: "uint256", internalType: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "hasVoted",
        inputs: [
            { name: "_voteId", type: "uint256", internalType: "uint256" },
            { name: "_voter", type: "address", internalType: "address" },
        ],
        outputs: [{ name: "_voted", type: "bool", internalType: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "initialize",
        inputs: [
            { name: "_orgFactory", type: "address", internalType: "address" },
            { name: "_meetingFactory", type: "address", internalType: "address" },
            { name: "_govToken", type: "address", internalType: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "revokeCollaboratorWeight",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_collaborator", type: "address", internalType: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setCircleMintCap",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_cap", type: "uint256", internalType: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setCircleQuorum",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_quorum", type: "uint256", internalType: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "event",
        name: "CircleMintCapSet",
        inputs: [
            { name: "_circleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_cap", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "CircleQuorumSet",
        inputs: [
            { name: "_circleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_quorum", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "CollaboratorWeightGranted",
        inputs: [
            { name: "_circleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_collaborator", type: "address", indexed: true, internalType: "address" },
            { name: "_weight", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "CollaboratorWeightRevoked",
        inputs: [
            { name: "_circleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_collaborator", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "VoteCast",
        inputs: [
            { name: "_voteId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_voter", type: "address", indexed: true, internalType: "address" },
            {
                name: "_support",
                type: "uint8",
                indexed: false,
                internalType: "enum HolacracyTypes.VoteSupport",
            },
            { name: "_weight", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "VoteCreated",
        inputs: [
            { name: "_voteId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_circleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_outputId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_proposer", type: "address", indexed: false, internalType: "address" },
            { name: "_deadline", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "_reason", type: "string", indexed: false, internalType: "string" },
            { name: "_snapshotBlock", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    { type: "error", name: "ActionVoting_AlreadyInitialized", inputs: [] },
    {
        type: "error",
        name: "ActionVoting_AlreadyVoted",
        inputs: [
            { name: "_voteId", type: "uint256", internalType: "uint256" },
            { name: "_voter", type: "address", internalType: "address" },
        ],
    },
    { type: "error", name: "ActionVoting_EmptyReason", inputs: [] },
    { type: "error", name: "ActionVoting_InvalidDuration", inputs: [] },
    {
        type: "error",
        name: "ActionVoting_MintCapExceeded",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_requested", type: "uint256", internalType: "uint256" },
            { name: "_remaining", type: "uint256", internalType: "uint256" },
        ],
    },
    {
        type: "error",
        name: "ActionVoting_NoVotingPower",
        inputs: [
            { name: "_voteId", type: "uint256", internalType: "uint256" },
            { name: "_voter", type: "address", internalType: "address" },
        ],
    },
    {
        type: "error",
        name: "ActionVoting_NotCircleLeadOrFacilitator",
        inputs: [{ name: "_circleId", type: "uint256", internalType: "uint256" }],
    },
    {
        type: "error",
        name: "ActionVoting_QuorumNotSet",
        inputs: [{ name: "_circleId", type: "uint256", internalType: "uint256" }],
    },
    {
        type: "error",
        name: "ActionVoting_VoteNotActive",
        inputs: [{ name: "_voteId", type: "uint256", internalType: "uint256" }],
    },
    {
        type: "error",
        name: "ActionVoting_VoteNotFound",
        inputs: [{ name: "_voteId", type: "uint256", internalType: "uint256" }],
    },
    { type: "error", name: "ActionVoting_ZeroAddress", inputs: [] },
    { type: "error", name: "ActionVoting_ZeroAmount", inputs: [] },
] as const;
