export const CircleRegistryAbi = [
    { type: "constructor", inputs: [], stateMutability: "nonpayable" },
    {
        type: "function",
        name: "acceptDeployerTransfer",
        inputs: [],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "addCircleLead",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_lead", type: "address", internalType: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "addPolicy",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_name", type: "string", internalType: "string" },
            { name: "_body", type: "string", internalType: "string" },
        ],
        outputs: [{ name: "_policyId", type: "uint256", internalType: "uint256" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "anchorCircleId",
        inputs: [],
        outputs: [{ name: "_circleId", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "assignRoleLeadInCircle",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_roleId", type: "uint256", internalType: "uint256" },
            { name: "_lead", type: "address", internalType: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "createAnchorCircle",
        inputs: [{ name: "_purpose", type: "string", internalType: "string" }],
        outputs: [{ name: "_circleId", type: "uint256", internalType: "uint256" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "createRoleInCircle",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_name", type: "string", internalType: "string" },
            { name: "_purpose", type: "string", internalType: "string" },
            { name: "_domains", type: "string[]", internalType: "string[]" },
            { name: "_accountabilities", type: "string[]", internalType: "string[]" },
        ],
        outputs: [{ name: "_roleId", type: "uint256", internalType: "uint256" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "createSubCircle",
        inputs: [{ name: "_roleId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "_circleId", type: "uint256", internalType: "uint256" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "deployer",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getCircle",
        inputs: [{ name: "_circleId", type: "uint256", internalType: "uint256" }],
        outputs: [
            {
                name: "_circle",
                type: "tuple",
                internalType: "struct HolacracyTypes.Circle",
                components: [
                    { name: "id", type: "uint256", internalType: "uint256" },
                    { name: "parentCircleId", type: "uint256", internalType: "uint256" },
                    { name: "roleId", type: "uint256", internalType: "uint256" },
                    { name: "name", type: "string", internalType: "string" },
                    { name: "purpose", type: "string", internalType: "string" },
                    { name: "isAnchor", type: "bool", internalType: "bool" },
                    { name: "exists", type: "bool", internalType: "bool" },
                ],
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getCircleLeads",
        inputs: [{ name: "_circleId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "_leads", type: "address[]", internalType: "address[]" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getCirclePolicies",
        inputs: [{ name: "_circleId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "_policyIds", type: "uint256[]", internalType: "uint256[]" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getElectedRole",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            {
                name: "_electedRole",
                type: "uint8",
                internalType: "enum HolacracyTypes.ElectedRole",
            },
        ],
        outputs: [{ name: "_account", type: "address", internalType: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getPolicy",
        inputs: [{ name: "_policyId", type: "uint256", internalType: "uint256" }],
        outputs: [
            {
                name: "_policy",
                type: "tuple",
                internalType: "struct HolacracyTypes.Policy",
                components: [
                    { name: "id", type: "uint256", internalType: "uint256" },
                    { name: "circleId", type: "uint256", internalType: "uint256" },
                    { name: "name", type: "string", internalType: "string" },
                    { name: "body", type: "string", internalType: "string" },
                    { name: "exists", type: "bool", internalType: "bool" },
                ],
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getSubCircles",
        inputs: [{ name: "_circleId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "_childIds", type: "uint256[]", internalType: "uint256[]" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "governanceProcess",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "initialize",
        inputs: [
            { name: "_roleRegistry", type: "address", internalType: "contract RoleRegistry" },
            { name: "_deployer", type: "address", internalType: "address" },
            { name: "_governanceProcess", type: "address", internalType: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "isCircleLead",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_account", type: "address", internalType: "address" },
        ],
        outputs: [{ name: "_isLead", type: "bool", internalType: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "isCircleMember",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_account", type: "address", internalType: "address" },
        ],
        outputs: [{ name: "_isMember", type: "bool", internalType: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "pendingDeployer",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "proposeDeployerTransfer",
        inputs: [{ name: "_newDeployer", type: "address", internalType: "address" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "removeCircleLead",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_lead", type: "address", internalType: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "removePolicy",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_policyId", type: "uint256", internalType: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "removeRoleFromCircle",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_roleId", type: "uint256", internalType: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "roleRegistry",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "contract RoleRegistry" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "roleToCircle",
        inputs: [{ name: "_roleId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "_circleId", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "setElectedRole",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            {
                name: "_electedRole",
                type: "uint8",
                internalType: "enum HolacracyTypes.ElectedRole",
            },
            { name: "_account", type: "address", internalType: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setGovernanceProcess",
        inputs: [{ name: "_governanceProcess", type: "address", internalType: "address" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "unassignRoleLeadInCircle",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_roleId", type: "uint256", internalType: "uint256" },
            { name: "_lead", type: "address", internalType: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "updateCircle",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_name", type: "string", internalType: "string" },
            { name: "_purpose", type: "string", internalType: "string" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "updateRoleInCircle",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_roleId", type: "uint256", internalType: "uint256" },
            { name: "_name", type: "string", internalType: "string" },
            { name: "_purpose", type: "string", internalType: "string" },
            { name: "_domains", type: "string[]", internalType: "string[]" },
            { name: "_accountabilities", type: "string[]", internalType: "string[]" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "event",
        name: "AnchorCircleCreated",
        inputs: [{ name: "_circleId", type: "uint256", indexed: true, internalType: "uint256" }],
        anonymous: false,
    },
    {
        type: "event",
        name: "CircleLeadAdded",
        inputs: [
            { name: "_circleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_lead", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "CircleLeadRemoved",
        inputs: [
            { name: "_circleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_lead", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "CircleRoleCreated",
        inputs: [
            { name: "_circleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_roleId", type: "uint256", indexed: true, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "CircleUpdated",
        inputs: [
            { name: "_circleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_name", type: "string", indexed: false, internalType: "string" },
            { name: "_purpose", type: "string", indexed: false, internalType: "string" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "DeployerTransferProposed",
        inputs: [
            { name: "_pendingDeployer", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "DeployerTransferred",
        inputs: [
            { name: "_oldDeployer", type: "address", indexed: true, internalType: "address" },
            { name: "_newDeployer", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ElectedRoleSet",
        inputs: [
            { name: "_circleId", type: "uint256", indexed: true, internalType: "uint256" },
            {
                name: "_electedRole",
                type: "uint8",
                indexed: true,
                internalType: "enum HolacracyTypes.ElectedRole",
            },
            { name: "_account", type: "address", indexed: false, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "PolicyAdded",
        inputs: [
            { name: "_circleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_policyId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_name", type: "string", indexed: false, internalType: "string" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "PolicyRemoved",
        inputs: [
            { name: "_circleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_policyId", type: "uint256", indexed: true, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RoleLeadAssignedViaCircle",
        inputs: [
            { name: "_circleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_roleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_lead", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "SubCircleCreated",
        inputs: [
            { name: "_circleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_parentCircleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_roleId", type: "uint256", indexed: true, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "error",
        name: "CircleRegistry_AlreadyCircleLead",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_lead", type: "address", internalType: "address" },
        ],
    },
    { type: "error", name: "CircleRegistry_AlreadyInitialized", inputs: [] },
    { type: "error", name: "CircleRegistry_AnchorAlreadyExists", inputs: [] },
    {
        type: "error",
        name: "CircleRegistry_CircleNotFound",
        inputs: [{ name: "_circleId", type: "uint256", internalType: "uint256" }],
    },
    { type: "error", name: "CircleRegistry_InvalidAddress", inputs: [] },
    {
        type: "error",
        name: "CircleRegistry_NotACircleLead",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_lead", type: "address", internalType: "address" },
        ],
    },
    {
        type: "error",
        name: "CircleRegistry_NotCircleLead",
        inputs: [{ name: "_circleId", type: "uint256", internalType: "uint256" }],
    },
    { type: "error", name: "CircleRegistry_NotPendingDeployer", inputs: [] },
    {
        type: "error",
        name: "CircleRegistry_PolicyNotFound",
        inputs: [{ name: "_policyId", type: "uint256", internalType: "uint256" }],
    },
    {
        type: "error",
        name: "CircleRegistry_RoleAlreadyCircle",
        inputs: [{ name: "_roleId", type: "uint256", internalType: "uint256" }],
    },
    {
        type: "error",
        name: "CircleRegistry_RoleNotInCircle",
        inputs: [
            { name: "_roleId", type: "uint256", internalType: "uint256" },
            { name: "_circleId", type: "uint256", internalType: "uint256" },
        ],
    },
    { type: "error", name: "CircleRegistry_Unauthorized", inputs: [] },
] as const;
