export const GovernanceProcessAbi = [
    { type: "constructor", inputs: [], stateMutability: "nonpayable" },
    {
        type: "function",
        name: "activateProposal",
        inputs: [{ name: "_proposalId", type: "uint256", internalType: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "adoptProposal",
        inputs: [{ name: "_proposalId", type: "uint256", internalType: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "circleRegistry",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "contract CircleRegistry" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "daoGovernor",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "discardProposal",
        inputs: [{ name: "_proposalId", type: "uint256", internalType: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "escalateToDAO",
        inputs: [
            { name: "_proposalId", type: "uint256", internalType: "uint256" },
            { name: "_description", type: "string", internalType: "string" },
        ],
        outputs: [{ name: "_daoProposalId", type: "uint256", internalType: "uint256" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "executeEscalatedProposal",
        inputs: [{ name: "_proposalId", type: "uint256", internalType: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "getCircleProposals",
        inputs: [{ name: "_circleId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "_proposalIds", type: "uint256[]", internalType: "uint256[]" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getObjection",
        inputs: [{ name: "_objectionId", type: "uint256", internalType: "uint256" }],
        outputs: [
            {
                name: "_objection",
                type: "tuple",
                internalType: "struct HolacracyTypes.Objection",
                components: [
                    { name: "id", type: "uint256", internalType: "uint256" },
                    { name: "proposalId", type: "uint256", internalType: "uint256" },
                    { name: "objectorRoleId", type: "uint256", internalType: "uint256" },
                    { name: "createdAt", type: "uint256", internalType: "uint256" },
                    { name: "isConstitutionalViolation", type: "bool", internalType: "bool" },
                    {
                        name: "status",
                        type: "uint8",
                        internalType: "enum HolacracyTypes.ObjectionStatus",
                    },
                    { name: "objector", type: "address", internalType: "address" },
                    { name: "concern", type: "string", internalType: "string" },
                    { name: "resolution", type: "string", internalType: "string" },
                ],
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getProposal",
        inputs: [{ name: "_proposalId", type: "uint256", internalType: "uint256" }],
        outputs: [
            {
                name: "_proposal",
                type: "tuple",
                internalType: "struct HolacracyTypes.Proposal",
                components: [
                    { name: "id", type: "uint256", internalType: "uint256" },
                    { name: "circleId", type: "uint256", internalType: "uint256" },
                    { name: "proposer", type: "address", internalType: "address" },
                    { name: "proposerRoleId", type: "uint256", internalType: "uint256" },
                    { name: "tension", type: "string", internalType: "string" },
                    { name: "example", type: "string", internalType: "string" },
                    { name: "explanation", type: "string", internalType: "string" },
                    {
                        name: "change",
                        type: "tuple",
                        internalType: "struct HolacracyTypes.GovernanceChange",
                        components: [
                            {
                                name: "changeType",
                                type: "uint8",
                                internalType: "enum HolacracyTypes.ChangeType",
                            },
                            { name: "targetId", type: "uint256", internalType: "uint256" },
                            { name: "encodedData", type: "bytes", internalType: "bytes" },
                        ],
                    },
                    {
                        name: "status",
                        type: "uint8",
                        internalType: "enum HolacracyTypes.ProposalStatus",
                    },
                    { name: "createdAt", type: "uint256", internalType: "uint256" },
                    { name: "resolvedAt", type: "uint256", internalType: "uint256" },
                ],
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getProposalObjections",
        inputs: [{ name: "_proposalId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "_objectionIds", type: "uint256[]", internalType: "uint256[]" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "initialize",
        inputs: [
            { name: "_circleRegistry", type: "address", internalType: "contract CircleRegistry" },
            { name: "_roleRegistry", type: "address", internalType: "contract RoleRegistry" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "invalidateObjection",
        inputs: [{ name: "_objectionId", type: "uint256", internalType: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "proposalCount",
        inputs: [],
        outputs: [{ name: "_count", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "raiseObjection",
        inputs: [
            { name: "_proposalId", type: "uint256", internalType: "uint256" },
            { name: "_objectorRoleId", type: "uint256", internalType: "uint256" },
            { name: "_concern", type: "string", internalType: "string" },
            { name: "_isConstitutionalViolation", type: "bool", internalType: "bool" },
        ],
        outputs: [{ name: "_objectionId", type: "uint256", internalType: "uint256" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "resolveObjection",
        inputs: [
            { name: "_objectionId", type: "uint256", internalType: "uint256" },
            { name: "_resolution", type: "string", internalType: "string" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "roleRegistry",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "contract RoleRegistry" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "setDAOGovernor",
        inputs: [
            { name: "_governor", type: "address", internalType: "address" },
            { name: "_timelock", type: "address", internalType: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "submitProposal",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_proposerRoleId", type: "uint256", internalType: "uint256" },
            { name: "_tension", type: "string", internalType: "string" },
            { name: "_example", type: "string", internalType: "string" },
            { name: "_explanation", type: "string", internalType: "string" },
            {
                name: "_change",
                type: "tuple",
                internalType: "struct HolacracyTypes.GovernanceChange",
                components: [
                    {
                        name: "changeType",
                        type: "uint8",
                        internalType: "enum HolacracyTypes.ChangeType",
                    },
                    { name: "targetId", type: "uint256", internalType: "uint256" },
                    { name: "encodedData", type: "bytes", internalType: "bytes" },
                ],
            },
        ],
        outputs: [{ name: "_proposalId", type: "uint256", internalType: "uint256" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "timelockController",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "withdrawProposal",
        inputs: [{ name: "_proposalId", type: "uint256", internalType: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "event",
        name: "DAOGovernorSet",
        inputs: [
            { name: "_governor", type: "address", indexed: true, internalType: "address" },
            { name: "_timelock", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ObjectionInvalidated",
        inputs: [
            { name: "_objectionId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_proposalId", type: "uint256", indexed: true, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ObjectionRaised",
        inputs: [
            { name: "_objectionId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_proposalId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_objector", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ObjectionResolved",
        inputs: [
            { name: "_objectionId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_proposalId", type: "uint256", indexed: true, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ProposalActivated",
        inputs: [{ name: "_proposalId", type: "uint256", indexed: true, internalType: "uint256" }],
        anonymous: false,
    },
    {
        type: "event",
        name: "ProposalAdopted",
        inputs: [{ name: "_proposalId", type: "uint256", indexed: true, internalType: "uint256" }],
        anonymous: false,
    },
    {
        type: "event",
        name: "ProposalDiscarded",
        inputs: [{ name: "_proposalId", type: "uint256", indexed: true, internalType: "uint256" }],
        anonymous: false,
    },
    {
        type: "event",
        name: "ProposalEscalated",
        inputs: [
            { name: "_proposalId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_daoProposalId", type: "uint256", indexed: true, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ProposalSubmitted",
        inputs: [
            { name: "_proposalId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_circleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_proposer", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ProposalWithdrawn",
        inputs: [{ name: "_proposalId", type: "uint256", indexed: true, internalType: "uint256" }],
        anonymous: false,
    },
    { type: "error", name: "GovernanceProcess_AlreadyInitialized", inputs: [] },
    { type: "error", name: "GovernanceProcess_DAOAlreadySet", inputs: [] },
    { type: "error", name: "GovernanceProcess_DAONotSet", inputs: [] },
    { type: "error", name: "GovernanceProcess_EmptyTension", inputs: [] },
    {
        type: "error",
        name: "GovernanceProcess_InvalidObjectionStatus",
        inputs: [
            { name: "_objectionId", type: "uint256", internalType: "uint256" },
            {
                name: "_expected",
                type: "uint8",
                internalType: "enum HolacracyTypes.ObjectionStatus",
            },
        ],
    },
    {
        type: "error",
        name: "GovernanceProcess_InvalidProposalStatus",
        inputs: [
            { name: "_proposalId", type: "uint256", internalType: "uint256" },
            {
                name: "_expected",
                type: "uint8",
                internalType: "enum HolacracyTypes.ProposalStatus",
            },
        ],
    },
    {
        type: "error",
        name: "GovernanceProcess_NotCircleMember",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_caller", type: "address", internalType: "address" },
        ],
    },
    {
        type: "error",
        name: "GovernanceProcess_NotFacilitator",
        inputs: [{ name: "_circleId", type: "uint256", internalType: "uint256" }],
    },
    {
        type: "error",
        name: "GovernanceProcess_NotProposer",
        inputs: [{ name: "_proposalId", type: "uint256", internalType: "uint256" }],
    },
    { type: "error", name: "GovernanceProcess_NotTimelock", inputs: [] },
    {
        type: "error",
        name: "GovernanceProcess_ObjectionNotFound",
        inputs: [{ name: "_objectionId", type: "uint256", internalType: "uint256" }],
    },
    {
        type: "error",
        name: "GovernanceProcess_ProposalNotFound",
        inputs: [{ name: "_proposalId", type: "uint256", internalType: "uint256" }],
    },
    {
        type: "error",
        name: "GovernanceProcess_UnresolvedObjections",
        inputs: [{ name: "_proposalId", type: "uint256", internalType: "uint256" }],
    },
] as const;
