export const HolacracyDataProviderAbi = [
    {
        type: "function",
        name: "getCircleProposals",
        inputs: [
            { name: "_governanceProcess", type: "address", internalType: "address" },
            { name: "_circleId", type: "uint256", internalType: "uint256" },
        ],
        outputs: [
            {
                name: "_proposals",
                type: "tuple[]",
                internalType: "struct IHolacracyDataProvider.ProposalSnapshot[]",
                components: [
                    { name: "id", type: "uint256", internalType: "uint256" },
                    { name: "circleId", type: "uint256", internalType: "uint256" },
                    { name: "proposer", type: "address", internalType: "address" },
                    { name: "proposerRoleId", type: "uint256", internalType: "uint256" },
                    { name: "tension", type: "string", internalType: "string" },
                    {
                        name: "status",
                        type: "uint8",
                        internalType: "enum HolacracyTypes.ProposalStatus",
                    },
                    { name: "createdAt", type: "uint256", internalType: "uint256" },
                    { name: "resolvedAt", type: "uint256", internalType: "uint256" },
                    { name: "objectionCount", type: "uint256", internalType: "uint256" },
                    { name: "unresolvedObjectionCount", type: "uint256", internalType: "uint256" },
                ],
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getOrganizationFullData",
        inputs: [
            { name: "_factory", type: "address", internalType: "address" },
            { name: "_orgId", type: "uint256", internalType: "uint256" },
        ],
        outputs: [
            {
                name: "_overview",
                type: "tuple",
                internalType: "struct IHolacracyDataProvider.OrganizationOverview",
                components: [
                    { name: "id", type: "uint256", internalType: "uint256" },
                    { name: "name", type: "string", internalType: "string" },
                    { name: "subname", type: "string", internalType: "string" },
                    { name: "creator", type: "address", internalType: "address" },
                    { name: "createdAt", type: "uint256", internalType: "uint256" },
                    { name: "roleRegistry", type: "address", internalType: "address" },
                    { name: "circleRegistry", type: "address", internalType: "address" },
                    { name: "governanceProcess", type: "address", internalType: "address" },
                    { name: "governor", type: "address", internalType: "address" },
                    { name: "token", type: "address", internalType: "address" },
                    { name: "timelock", type: "address", internalType: "address" },
                    { name: "tokenName", type: "string", internalType: "string" },
                    { name: "tokenSymbol", type: "string", internalType: "string" },
                    { name: "tokenTotalSupply", type: "uint256", internalType: "uint256" },
                    { name: "governorName", type: "string", internalType: "string" },
                    { name: "votingDelay", type: "uint256", internalType: "uint256" },
                    { name: "votingPeriod", type: "uint256", internalType: "uint256" },
                    { name: "proposalThreshold", type: "uint256", internalType: "uint256" },
                    { name: "quorumNumerator", type: "uint256", internalType: "uint256" },
                    { name: "circleCount", type: "uint256", internalType: "uint256" },
                    { name: "roleCount", type: "uint256", internalType: "uint256" },
                    { name: "proposalCount", type: "uint256", internalType: "uint256" },
                ],
            },
            {
                name: "_circles",
                type: "tuple[]",
                internalType: "struct IHolacracyDataProvider.CircleSnapshot[]",
                components: [
                    { name: "id", type: "uint256", internalType: "uint256" },
                    { name: "parentCircleId", type: "uint256", internalType: "uint256" },
                    { name: "roleId", type: "uint256", internalType: "uint256" },
                    { name: "name", type: "string", internalType: "string" },
                    { name: "purpose", type: "string", internalType: "string" },
                    { name: "isAnchor", type: "bool", internalType: "bool" },
                    { name: "circleLeads", type: "address[]", internalType: "address[]" },
                    { name: "facilitator", type: "address", internalType: "address" },
                    { name: "secretary", type: "address", internalType: "address" },
                    { name: "circleRep", type: "address", internalType: "address" },
                    { name: "roleIds", type: "uint256[]", internalType: "uint256[]" },
                    { name: "subCircleIds", type: "uint256[]", internalType: "uint256[]" },
                    { name: "policyIds", type: "uint256[]", internalType: "uint256[]" },
                    { name: "openProposalCount", type: "uint256", internalType: "uint256" },
                    { name: "totalProposalCount", type: "uint256", internalType: "uint256" },
                ],
            },
            {
                name: "_roles",
                type: "tuple[]",
                internalType: "struct IHolacracyDataProvider.RoleSnapshot[]",
                components: [
                    { name: "id", type: "uint256", internalType: "uint256" },
                    { name: "circleId", type: "uint256", internalType: "uint256" },
                    { name: "name", type: "string", internalType: "string" },
                    { name: "purpose", type: "string", internalType: "string" },
                    { name: "domains", type: "string[]", internalType: "string[]" },
                    { name: "accountabilities", type: "string[]", internalType: "string[]" },
                    { name: "leads", type: "address[]", internalType: "address[]" },
                    { name: "isExpandedToCircle", type: "bool", internalType: "bool" },
                    { name: "expandedCircleId", type: "uint256", internalType: "uint256" },
                ],
            },
            {
                name: "_policies",
                type: "tuple[]",
                internalType: "struct IHolacracyDataProvider.PolicySnapshot[]",
                components: [
                    { name: "id", type: "uint256", internalType: "uint256" },
                    { name: "circleId", type: "uint256", internalType: "uint256" },
                    { name: "name", type: "string", internalType: "string" },
                    { name: "body", type: "string", internalType: "string" },
                ],
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getOrganizationOverview",
        inputs: [
            { name: "_factory", type: "address", internalType: "address" },
            { name: "_orgId", type: "uint256", internalType: "uint256" },
        ],
        outputs: [
            {
                name: "_overview",
                type: "tuple",
                internalType: "struct IHolacracyDataProvider.OrganizationOverview",
                components: [
                    { name: "id", type: "uint256", internalType: "uint256" },
                    { name: "name", type: "string", internalType: "string" },
                    { name: "subname", type: "string", internalType: "string" },
                    { name: "creator", type: "address", internalType: "address" },
                    { name: "createdAt", type: "uint256", internalType: "uint256" },
                    { name: "roleRegistry", type: "address", internalType: "address" },
                    { name: "circleRegistry", type: "address", internalType: "address" },
                    { name: "governanceProcess", type: "address", internalType: "address" },
                    { name: "governor", type: "address", internalType: "address" },
                    { name: "token", type: "address", internalType: "address" },
                    { name: "timelock", type: "address", internalType: "address" },
                    { name: "tokenName", type: "string", internalType: "string" },
                    { name: "tokenSymbol", type: "string", internalType: "string" },
                    { name: "tokenTotalSupply", type: "uint256", internalType: "uint256" },
                    { name: "governorName", type: "string", internalType: "string" },
                    { name: "votingDelay", type: "uint256", internalType: "uint256" },
                    { name: "votingPeriod", type: "uint256", internalType: "uint256" },
                    { name: "proposalThreshold", type: "uint256", internalType: "uint256" },
                    { name: "quorumNumerator", type: "uint256", internalType: "uint256" },
                    { name: "circleCount", type: "uint256", internalType: "uint256" },
                    { name: "roleCount", type: "uint256", internalType: "uint256" },
                    { name: "proposalCount", type: "uint256", internalType: "uint256" },
                ],
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getUserOrgData",
        inputs: [
            { name: "_factory", type: "address", internalType: "address" },
            { name: "_orgId", type: "uint256", internalType: "uint256" },
            { name: "_user", type: "address", internalType: "address" },
        ],
        outputs: [
            {
                name: "_data",
                type: "tuple",
                internalType: "struct IHolacracyDataProvider.UserOrgData",
                components: [
                    { name: "user", type: "address", internalType: "address" },
                    { name: "tokenBalance", type: "uint256", internalType: "uint256" },
                    { name: "votingPower", type: "uint256", internalType: "uint256" },
                    { name: "delegate", type: "address", internalType: "address" },
                    { name: "ledRoleIds", type: "uint256[]", internalType: "uint256[]" },
                    { name: "leadCircleIds", type: "uint256[]", internalType: "uint256[]" },
                    { name: "memberCircleIds", type: "uint256[]", internalType: "uint256[]" },
                    {
                        name: "facilitatorOfCircleIds",
                        type: "uint256[]",
                        internalType: "uint256[]",
                    },
                    { name: "secretaryOfCircleIds", type: "uint256[]", internalType: "uint256[]" },
                    { name: "circleRepOfCircleIds", type: "uint256[]", internalType: "uint256[]" },
                ],
            },
        ],
        stateMutability: "view",
    },
] as const;
