export const RoleRegistryAbi = [
    { type: "constructor", inputs: [], stateMutability: "nonpayable" },
    {
        type: "function",
        name: "assignRoleLead",
        inputs: [
            { name: "_roleId", type: "uint256", internalType: "uint256" },
            { name: "_lead", type: "address", internalType: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "circleRegistry",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "createRole",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_name", type: "string", internalType: "string" },
            { name: "_purpose", type: "string", internalType: "string" },
            { name: "_domains", type: "string[]", internalType: "string[]" },
            { name: "_accountabilities", type: "string[]", internalType: "string[]" },
        ],
        outputs: [{ name: "_roleId", type: "uint256", internalType: "uint256" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "getCircleRoleIds",
        inputs: [{ name: "_circleId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "_roleIds", type: "uint256[]", internalType: "uint256[]" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getRole",
        inputs: [{ name: "_roleId", type: "uint256", internalType: "uint256" }],
        outputs: [
            {
                name: "_role",
                type: "tuple",
                internalType: "struct HolacracyTypes.Role",
                components: [
                    { name: "id", type: "uint256", internalType: "uint256" },
                    { name: "circleId", type: "uint256", internalType: "uint256" },
                    { name: "name", type: "string", internalType: "string" },
                    { name: "purpose", type: "string", internalType: "string" },
                    { name: "domains", type: "string[]", internalType: "string[]" },
                    { name: "accountabilities", type: "string[]", internalType: "string[]" },
                    { name: "exists", type: "bool", internalType: "bool" },
                ],
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getRoleAccountabilities",
        inputs: [{ name: "_roleId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "_accountabilities", type: "string[]", internalType: "string[]" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getRoleDomains",
        inputs: [{ name: "_roleId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "_domains", type: "string[]", internalType: "string[]" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getRoleLeads",
        inputs: [{ name: "_roleId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "_leads", type: "address[]", internalType: "address[]" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "initialize",
        inputs: [],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "isRoleLead",
        inputs: [
            { name: "_roleId", type: "uint256", internalType: "uint256" },
            { name: "_account", type: "address", internalType: "address" },
        ],
        outputs: [{ name: "_isLead", type: "bool", internalType: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "removeRole",
        inputs: [{ name: "_roleId", type: "uint256", internalType: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "roleCount",
        inputs: [],
        outputs: [{ name: "_count", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "setCircleRegistry",
        inputs: [{ name: "_circleRegistry", type: "address", internalType: "address" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "unassignRoleLead",
        inputs: [
            { name: "_roleId", type: "uint256", internalType: "uint256" },
            { name: "_lead", type: "address", internalType: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "updateRole",
        inputs: [
            { name: "_roleId", type: "uint256", internalType: "uint256" },
            { name: "_name", type: "string", internalType: "string" },
            { name: "_purpose", type: "string", internalType: "string" },
            { name: "_domains", type: "string[]", internalType: "string[]" },
            { name: "_accountabilities", type: "string[]", internalType: "string[]" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "event",
        name: "RoleCreated",
        inputs: [
            { name: "_roleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_circleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_name", type: "string", indexed: false, internalType: "string" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RoleLeadAssigned",
        inputs: [
            { name: "_roleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_lead", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RoleLeadUnassigned",
        inputs: [
            { name: "_roleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_lead", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RoleRemoved",
        inputs: [
            { name: "_roleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_circleId", type: "uint256", indexed: true, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RoleUpdated",
        inputs: [{ name: "_roleId", type: "uint256", indexed: true, internalType: "uint256" }],
        anonymous: false,
    },
    { type: "error", name: "RoleRegistry_AlreadyInitialized", inputs: [] },
    {
        type: "error",
        name: "RoleRegistry_AlreadyRoleLead",
        inputs: [
            { name: "_roleId", type: "uint256", internalType: "uint256" },
            { name: "_lead", type: "address", internalType: "address" },
        ],
    },
    { type: "error", name: "RoleRegistry_EmptyName", inputs: [] },
    { type: "error", name: "RoleRegistry_InvalidRole", inputs: [] },
    {
        type: "error",
        name: "RoleRegistry_NotRoleLead",
        inputs: [
            { name: "_roleId", type: "uint256", internalType: "uint256" },
            { name: "_lead", type: "address", internalType: "address" },
        ],
    },
    {
        type: "error",
        name: "RoleRegistry_RoleNotFound",
        inputs: [{ name: "_roleId", type: "uint256", internalType: "uint256" }],
    },
    { type: "error", name: "RoleRegistry_Unauthorized", inputs: [] },
] as const;
