export const TacticalMeetingAbi = [
    { type: "constructor", inputs: [], stateMutability: "nonpayable" },
    {
        type: "function",
        name: "addChecklistItem",
        inputs: [
            { name: "_roleId", type: "uint256", internalType: "uint256" },
            { name: "_label", type: "string", internalType: "string" },
        ],
        outputs: [{ name: "_checklistItemId", type: "uint256", internalType: "uint256" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "addMetric",
        inputs: [
            { name: "_roleId", type: "uint256", internalType: "uint256" },
            { name: "_label", type: "string", internalType: "string" },
        ],
        outputs: [{ name: "_metricId", type: "uint256", internalType: "uint256" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "circleRegistry",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "contract CircleRegistry" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "completeMeeting",
        inputs: [{ name: "_meetingId", type: "uint256", internalType: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "conveneMeeting",
        inputs: [{ name: "_circleId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "_meetingId", type: "uint256", internalType: "uint256" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "getChecklistItem",
        inputs: [{ name: "_checklistItemId", type: "uint256", internalType: "uint256" }],
        outputs: [
            {
                name: "_item",
                type: "tuple",
                internalType: "struct HolacracyTypes.ChecklistItem",
                components: [
                    { name: "id", type: "uint256", internalType: "uint256" },
                    { name: "roleId", type: "uint256", internalType: "uint256" },
                    { name: "label", type: "string", internalType: "string" },
                    { name: "exists", type: "bool", internalType: "bool" },
                ],
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getCircleMeetings",
        inputs: [{ name: "_circleId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "_meetingIds", type: "uint256[]", internalType: "uint256[]" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getMeeting",
        inputs: [{ name: "_meetingId", type: "uint256", internalType: "uint256" }],
        outputs: [
            {
                name: "_meeting",
                type: "tuple",
                internalType: "struct HolacracyTypes.TacticalMeeting",
                components: [
                    { name: "id", type: "uint256", internalType: "uint256" },
                    { name: "circleId", type: "uint256", internalType: "uint256" },
                    { name: "convenedBy", type: "address", internalType: "address" },
                    { name: "createdAt", type: "uint256", internalType: "uint256" },
                    { name: "completedAt", type: "uint256", internalType: "uint256" },
                    { name: "exists", type: "bool", internalType: "bool" },
                ],
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getMeetingOutputs",
        inputs: [{ name: "_meetingId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "_outputIds", type: "uint256[]", internalType: "uint256[]" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getMetric",
        inputs: [{ name: "_metricId", type: "uint256", internalType: "uint256" }],
        outputs: [
            {
                name: "_metric",
                type: "tuple",
                internalType: "struct HolacracyTypes.Metric",
                components: [
                    { name: "id", type: "uint256", internalType: "uint256" },
                    { name: "roleId", type: "uint256", internalType: "uint256" },
                    { name: "label", type: "string", internalType: "string" },
                    { name: "exists", type: "bool", internalType: "bool" },
                ],
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getOutput",
        inputs: [{ name: "_outputId", type: "uint256", internalType: "uint256" }],
        outputs: [
            {
                name: "_output",
                type: "tuple",
                internalType: "struct HolacracyTypes.MeetingOutput",
                components: [
                    { name: "id", type: "uint256", internalType: "uint256" },
                    { name: "meetingId", type: "uint256", internalType: "uint256" },
                    {
                        name: "outputType",
                        type: "uint8",
                        internalType: "enum HolacracyTypes.OutputType",
                    },
                    { name: "description", type: "string", internalType: "string" },
                    { name: "assignedTo", type: "address", internalType: "address" },
                    { name: "roleId", type: "uint256", internalType: "uint256" },
                    { name: "createdAt", type: "uint256", internalType: "uint256" },
                ],
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getRoleChecklistItems",
        inputs: [{ name: "_roleId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "_itemIds", type: "uint256[]", internalType: "uint256[]" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getRoleMetrics",
        inputs: [{ name: "_roleId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "_metricIds", type: "uint256[]", internalType: "uint256[]" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "initialize",
        inputs: [
            { name: "_circleRegistry", type: "address", internalType: "contract CircleRegistry" },
            { name: "_roleRegistry", type: "address", internalType: "contract RoleRegistry" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "recordOutput",
        inputs: [
            { name: "_meetingId", type: "uint256", internalType: "uint256" },
            {
                name: "_outputType",
                type: "uint8",
                internalType: "enum HolacracyTypes.OutputType",
            },
            { name: "_description", type: "string", internalType: "string" },
            { name: "_assignedTo", type: "address", internalType: "address" },
            { name: "_roleId", type: "uint256", internalType: "uint256" },
        ],
        outputs: [{ name: "_outputId", type: "uint256", internalType: "uint256" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "removeChecklistItem",
        inputs: [{ name: "_checklistItemId", type: "uint256", internalType: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "removeMetric",
        inputs: [{ name: "_metricId", type: "uint256", internalType: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "roleRegistry",
        inputs: [],
        outputs: [{ name: "", type: "address", internalType: "contract RoleRegistry" }],
        stateMutability: "view",
    },
    {
        type: "event",
        name: "ChecklistItemAdded",
        inputs: [
            { name: "_roleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_checklistItemId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_label", type: "string", indexed: false, internalType: "string" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ChecklistItemRemoved",
        inputs: [
            { name: "_roleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_checklistItemId", type: "uint256", indexed: true, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "MeetingCompleted",
        inputs: [{ name: "_meetingId", type: "uint256", indexed: true, internalType: "uint256" }],
        anonymous: false,
    },
    {
        type: "event",
        name: "MeetingConvened",
        inputs: [
            { name: "_meetingId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_circleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_convenedBy", type: "address", indexed: true, internalType: "address" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "MetricAdded",
        inputs: [
            { name: "_roleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_metricId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_label", type: "string", indexed: false, internalType: "string" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "MetricRemoved",
        inputs: [
            { name: "_roleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_metricId", type: "uint256", indexed: true, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "OutputRecorded",
        inputs: [
            { name: "_meetingId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "_outputId", type: "uint256", indexed: true, internalType: "uint256" },
            {
                name: "_outputType",
                type: "uint8",
                indexed: true,
                internalType: "enum HolacracyTypes.OutputType",
            },
            { name: "_assignedTo", type: "address", indexed: false, internalType: "address" },
        ],
        anonymous: false,
    },
    { type: "error", name: "TacticalMeeting_AlreadyInitialized", inputs: [] },
    {
        type: "error",
        name: "TacticalMeeting_ChecklistItemNotFound",
        inputs: [{ name: "_checklistItemId", type: "uint256", internalType: "uint256" }],
    },
    { type: "error", name: "TacticalMeeting_EmptyString", inputs: [] },
    {
        type: "error",
        name: "TacticalMeeting_MeetingAlreadyCompleted",
        inputs: [{ name: "_meetingId", type: "uint256", internalType: "uint256" }],
    },
    {
        type: "error",
        name: "TacticalMeeting_MeetingNotFound",
        inputs: [{ name: "_meetingId", type: "uint256", internalType: "uint256" }],
    },
    {
        type: "error",
        name: "TacticalMeeting_MetricNotFound",
        inputs: [{ name: "_metricId", type: "uint256", internalType: "uint256" }],
    },
    {
        type: "error",
        name: "TacticalMeeting_NotCircleLead",
        inputs: [{ name: "_circleId", type: "uint256", internalType: "uint256" }],
    },
    {
        type: "error",
        name: "TacticalMeeting_NotCircleMember",
        inputs: [
            { name: "_circleId", type: "uint256", internalType: "uint256" },
            { name: "_caller", type: "address", internalType: "address" },
        ],
    },
    {
        type: "error",
        name: "TacticalMeeting_NotFacilitator",
        inputs: [{ name: "_meetingId", type: "uint256", internalType: "uint256" }],
    },
] as const;
