#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# dev-local.sh — One-command local development with Anvil
#
# Starts anvil, deploys the full contract stack, regenerates wagmi bindings
# (so the frontend reads addresses from broadcast artifacts), writes .env.local
# for the indexer, then launches ponder + vite in parallel.
#
# Usage:
#   ./scripts/dev-local.sh          # start everything
#   ./scripts/dev-local.sh --deploy # only anvil + deploy (no frontend/indexer)
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONTRACTS="$ROOT/packages/contracts"
FRONTEND="$ROOT/apps/hola-modern"
INDEXER="$ROOT/apps/hollab-indexing"
ARTIFACT="$CONTRACTS/deployments/31337-local.json"
ANVIL_PORT=8545
ANVIL_PID=""
PIDS=()

# ── Cleanup on exit ──────────────────────────────────────────────────────────
cleanup() {
  echo ""
  echo "Shutting down..."
  for pid in "${PIDS[@]}"; do
    kill "$pid" 2>/dev/null || true
  done
  if [ -n "$ANVIL_PID" ]; then
    kill "$ANVIL_PID" 2>/dev/null || true
  fi
  wait 2>/dev/null || true
  echo "Done."
}
trap cleanup EXIT INT TERM

# ── Check prerequisites ──────────────────────────────────────────────────────
for cmd in anvil forge jq pnpm; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "Error: $cmd is required but not found. Please install it first."
    exit 1
  fi
done

# ── 1. Start Anvil ──────────────────────────────────────────────────────────
echo "Starting Anvil on port $ANVIL_PORT..."
anvil --port "$ANVIL_PORT" --silent &
ANVIL_PID=$!

# Wait for anvil to be ready
for i in $(seq 1 30); do
  if cast chain-id --rpc-url "http://127.0.0.1:$ANVIL_PORT" &>/dev/null; then
    break
  fi
  if [ "$i" -eq 30 ]; then
    echo "Error: Anvil failed to start"
    exit 1
  fi
  sleep 0.2
done
echo "Anvil running (PID $ANVIL_PID)"

# ── 2. Deploy contracts ─────────────────────────────────────────────────────
echo ""
echo "Deploying contracts to local anvil..."
mkdir -p "$CONTRACTS/deployments"
(cd "$CONTRACTS" && forge script script/DeployLocal.s.sol \
  --tc DeployLocal \
  --rpc-url "http://127.0.0.1:$ANVIL_PORT" \
  --broadcast -vvv)

# ── 3. Fund test addresses ───────────────────────────────────────────────────
FUND_ADDRESSES_FILE="$ROOT/scripts/fund-addresses.local"
ANVIL_PRIVATE_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
if [ -f "$FUND_ADDRESSES_FILE" ]; then
  echo ""
  echo "Funding test addresses..."
  while IFS= read -r addr || [ -n "$addr" ]; do
    addr=$(echo "$addr" | xargs)  # trim whitespace
    [[ -z "$addr" || "$addr" == \#* ]] && continue  # skip empty/comments
    cast send "$addr" --value 100ether \
      --rpc-url "http://127.0.0.1:$ANVIL_PORT" \
      --private-key "$ANVIL_PRIVATE_KEY" > /dev/null
    echo "  Funded $addr (100 ETH)"
  done < "$FUND_ADDRESSES_FILE"
fi

# ── 4. Regenerate wagmi bindings (picks up broadcast addresses) ──────────────
echo ""
echo "Regenerating wagmi bindings..."
(cd "$CONTRACTS" && pnpm generate)

# ── 4. Extract addresses for indexer .env.local ──────────────────────────────
if [ ! -f "$ARTIFACT" ]; then
  echo "Error: Deployment artifact not found at $ARTIFACT"
  exit 1
fi

ORG_FACTORY=$(jq -r '.orgFactory' "$ARTIFACT")
GOV_FACTORY=$(jq -r '.govFactory' "$ARTIFACT")
MEETING_FACTORY=$(jq -r '.meetingFactory' "$ARTIFACT")
JOIN_REQUEST=$(jq -r '.joinRequest' "$ARTIFACT")
TENSION_BOARD=$(jq -r '.tensionBoard' "$ARTIFACT")
DATA_PROVIDER=$(jq -r '.dataProvider' "$ARTIFACT")

echo ""
echo "Deployed addresses:"
echo "  OrganizationFactory:      $ORG_FACTORY"
echo "  HolGovernorFactory:       $GOV_FACTORY"
echo "  MeetingComponentsFactory: $MEETING_FACTORY"
echo "  JoinRequest:              $JOIN_REQUEST"
echo "  TensionBoard:             $TENSION_BOARD"
echo "  HolacracyDataProvider:    $DATA_PROVIDER"

# ── 5. Write .env.local files ────────────────────────────────────────────────
# Frontend: only addresses not yet in wagmi-generated output
cat > "$FRONTEND/.env.local" <<EOF
# Auto-generated by dev-local.sh — do not commit
VITE_LOCAL_JOIN_REQUEST_ADDRESS=$JOIN_REQUEST
VITE_LOCAL_TENSION_BOARD_ADDRESS=$TENSION_BOARD
EOF
echo "Wrote $FRONTEND/.env.local"

# Indexer: ponder needs all addresses via env vars
cat > "$INDEXER/.env.local" <<EOF
# Auto-generated by dev-local.sh — do not commit
PONDER_CHAIN=localhost
PONDER_RPC_URL=http://127.0.0.1:$ANVIL_PORT
START_BLOCK=0
ORGANIZATION_FACTORY_ADDRESS=$ORG_FACTORY
HOL_GOVERNOR_FACTORY_ADDRESS=$GOV_FACTORY
MEETING_COMPONENTS_FACTORY_ADDRESS=$MEETING_FACTORY
JOIN_REQUEST_ADDRESS=$JOIN_REQUEST
TENSION_BOARD_ADDRESS=$TENSION_BOARD
HOLACRACY_DATA_PROVIDER_ADDRESS=$DATA_PROVIDER
EOF
echo "Wrote $INDEXER/.env.local"

# ── Early exit if --deploy only ──────────────────────────────────────────────
if [ "${1:-}" = "--deploy" ]; then
  echo ""
  echo "Deploy-only mode. Anvil running on http://127.0.0.1:$ANVIL_PORT"
  echo "Press Ctrl+C to stop."
  wait "$ANVIL_PID"
  exit 0
fi

# ── 6. Start Ponder indexer ──────────────────────────────────────────────────
echo ""
echo "Starting Ponder indexer..."
(cd "$INDEXER" && pnpm dev) &
PIDS+=($!)

# Give ponder a moment to start before launching vite
sleep 2

# ── 7. Start Vite frontend ──────────────────────────────────────────────────
echo "Starting Vite dev server..."
(cd "$FRONTEND" && pnpm dev) &
PIDS+=($!)

echo ""
echo "========================================="
echo "  Local dev environment ready!"
echo ""
echo "  Anvil:    http://127.0.0.1:$ANVIL_PORT"
echo "  Indexer:  http://localhost:42069"
echo "  Frontend: http://localhost:5173"
echo ""
echo "  Chain ID: 31337 (Foundry/Anvil)"
echo "  Press Ctrl+C to stop all services"
echo "========================================="
echo ""

# Wait for any child to exit
wait
