#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# dev-sepolia.sh — Run ponder + frontend locally against live Sepolia
#
# No anvil. No redeploy. Reads infrastructure addresses from
# packages/contracts/deployments/11155111-infrastructure.json, writes
# .env.local for both the indexer and the frontend, then launches ponder
# (pointed at Sepolia) and vite (pointed at local ponder) in parallel.
#
# Reads and writes happen on real Sepolia; only the indexer + UI are local.
#
# Usage:
#   ./scripts/dev-sepolia.sh
#
# Required env (in your shell or packages/contracts/.env):
#   ETH_SEPOLIA_RPC_URL   — production RPC (e.g. DRPC)
#
# Optional env:
#   START_BLOCK           — override ponder backfill start (default: 10665310)
#   VITE_WALLETCONNECT_PROJECT_ID
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONTRACTS="$ROOT/packages/contracts"
FRONTEND="$ROOT/apps/hola-modern"
INDEXER="$ROOT/apps/hollab-indexing"
ARTIFACT="$CONTRACTS/deployments/11155111-infrastructure.json"
DEFAULT_START_BLOCK=10665310
PIDS=()

# ── Cleanup on exit ──────────────────────────────────────────────────────────
cleanup() {
  echo ""
  echo "Shutting down..."
  for pid in "${PIDS[@]}"; do
    kill "$pid" 2>/dev/null || true
  done
  wait 2>/dev/null || true
  echo "Done."
}
trap cleanup EXIT INT TERM

# ── Prereqs ──────────────────────────────────────────────────────────────────
for cmd in jq pnpm; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "Error: $cmd is required but not found."
    exit 1
  fi
done

# ── Load contracts .env (for ETH_SEPOLIA_RPC_URL) ────────────────────────────
if [ -f "$CONTRACTS/.env" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$CONTRACTS/.env"
  set +a
fi

: "${ETH_SEPOLIA_RPC_URL:?ETH_SEPOLIA_RPC_URL is required (set in packages/contracts/.env or export in shell)}"

if [ ! -f "$ARTIFACT" ]; then
  echo "Error: Sepolia deployment artifact not found at $ARTIFACT"
  echo "Run 'pnpm --filter @hollab-io/contracts deploy:infra:sepolia' first."
  exit 1
fi

# ── Extract addresses ────────────────────────────────────────────────────────
ORG_FACTORY=$(jq -r '.orgFactory' "$ARTIFACT")
MEETING_FACTORY=$(jq -r '.meetingFactory' "$ARTIFACT")
ENS_REGISTRAR=$(jq -r '.ensRegistrar' "$ARTIFACT")

if [ "$ORG_FACTORY" = "null" ] || [ -z "$ORG_FACTORY" ]; then
  echo "Error: .orgFactory missing from $ARTIFACT"
  exit 1
fi
if [ "$MEETING_FACTORY" = "null" ] || [ -z "$MEETING_FACTORY" ]; then
  echo "Error: .meetingFactory missing from $ARTIFACT"
  exit 1
fi

START_BLOCK="${START_BLOCK:-$DEFAULT_START_BLOCK}"

echo "Sepolia infrastructure:"
echo "  OrganizationFactory:      $ORG_FACTORY"
echo "  MeetingComponentsFactory: $MEETING_FACTORY"
echo "  ENSSubdomainRegistrar:    $ENS_REGISTRAR"
echo "  START_BLOCK:              $START_BLOCK"

# ── Write indexer .env.local ─────────────────────────────────────────────────
cat > "$INDEXER/.env.local" <<EOF
# Auto-generated by dev-sepolia.sh — do not commit
PONDER_CHAIN=sepolia
PONDER_RPC_URL=$ETH_SEPOLIA_RPC_URL
START_BLOCK=$START_BLOCK
ORGANIZATION_FACTORY_ADDRESS=$ORG_FACTORY
MEETING_COMPONENTS_FACTORY_ADDRESS=$MEETING_FACTORY
EOF
echo "Wrote $INDEXER/.env.local"

# ── Write frontend .env.local ────────────────────────────────────────────────
FRONTEND_ENV="$FRONTEND/.env.local"
cat > "$FRONTEND_ENV" <<EOF
# Auto-generated by dev-sepolia.sh — do not commit
VITE_INDEXER_URL_SEPOLIA=http://localhost:42069
EOF
if [ -n "${VITE_WALLETCONNECT_PROJECT_ID:-}" ]; then
  echo "VITE_WALLETCONNECT_PROJECT_ID=$VITE_WALLETCONNECT_PROJECT_ID" >> "$FRONTEND_ENV"
fi
echo "Wrote $FRONTEND_ENV"

# ── Clear stale ponder cache (old addresses) ─────────────────────────────────
if [ -d "$INDEXER/.ponder" ]; then
  echo "Clearing stale ponder cache..."
  rm -rf "$INDEXER/.ponder"
fi

# ── Start Ponder (live-synced against Sepolia) ───────────────────────────────
echo ""
echo "Starting Ponder against Sepolia (backfill from block $START_BLOCK)..."
(cd "$INDEXER" && pnpm dev) &
PIDS+=($!)

sleep 3

# ── Start Vite frontend ──────────────────────────────────────────────────────
echo "Starting Vite dev server..."
(cd "$FRONTEND" && pnpm dev) &
PIDS+=($!)

echo ""
echo "========================================="
echo "  Sepolia dev environment ready!"
echo ""
echo "  Chain:    Sepolia (11155111)"
echo "  RPC:      $ETH_SEPOLIA_RPC_URL"
echo "  Indexer:  http://localhost:42069  (local → Sepolia)"
echo "  Frontend: http://localhost:5173   (reads → local indexer)"
echo ""
echo "  Wallet writes go to real Sepolia."
echo "  Press Ctrl+C to stop all services."
echo "========================================="
echo ""

wait
